### ISSUE TITLE
Sessions are disabled for this entry point (BootstrapComponents\ParserOutputHelper->detectSkinInUse)

### ISSUE THREAD

**Issue by mwjames** [oetterer/BootstrapComponents#9]
## Setup

- MediaWiki | 1.30.0 (4998ed3)23:28, 7. Feb. 2018
- PHP | 7.0.27-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Chameleon | 1.6.1-alpha (476efef) 08:44, 18. Jan. 2018
- Bootstrap | 1.2.3 (cdb1d58) 23:23, 30. Nov. 2017
- BootstrapComponents | 1.1.1 (ecb46da) 18:36, 6. Feb. 2018

## Issue

![image](https://user-images.githubusercontent.com/1245473/36340033-8fdfcd96-13ca-11e8-9eb8-1741687f3ea8.png)

### What?

```
4a7e98c5b8d113b50bdfe966] /w/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector   BadMethodCallException from line 847 of /../w/includes/session/SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 /../w/includes/session/SessionManager.php(195): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
#1 /../w/includes/WebRequest.php(735): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#2 /../w/includes/user/User.php(1231): WebRequest->getSession()
#3 /../w/includes/user/User.php(408): User->loadFromSession()
#4 /../w/includes/user/User.php(5266): User->load()
#5 /../w/includes/user/User.php(2884): User->loadOptions()
#6 /../w/includes/context/RequestContext.php(423): User->getOption(string)
#7 /../w/extensions/BootstrapComponents/src/ParserOutputHelper.php(243): RequestContext->getSkin()
#8 /../w/extensions/BootstrapComponents/src/ParserOutputHelper.php(100): BootstrapComponents\ParserOutputHelper->detectSkinInUse()
#9 [internal function]: BootstrapComponents\ParserOutputHelper->__construct(Parser)
#10 /../w/extensions/BootstrapComponents/src/ApplicationFactory.php(233): ReflectionClass->newInstanceArgs(array)
#11 /../w/extensions/BootstrapComponents/src/ApplicationFactory.php(159): BootstrapComponents\ApplicationFactory->getApplication(string, Parser)
#12 /../w/extensions/BootstrapComponents/src/Setup.php(401): BootstrapComponents\ApplicationFactory->getParserOutputHelper(Parser)
#13 /../w/includes/Hooks.php(177): BootstrapComponents\Setup->BootstrapComponents\{closure}(Parser)
#14 /../w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#15 /../w/includes/parser/Parser.php(337): Hooks::run(string, array)
#16 /../w/extensions/CodeMirror/ResourceLoaderCodeMirrorModule.php(70): Parser->firstCallInit()
#17 /../w/extensions/CodeMirror/ResourceLoaderCodeMirrorModule.php(32): ResourceLoaderCodeMirrorModule->getFrontendConfiguraton()
#18 /../w/includes/resourceloader/ResourceLoaderModule.php(719): ResourceLoaderCodeMirrorModule->getScript(DerivativeResourceLoaderContext)
#19 /../w/includes/resourceloader/ResourceLoaderModule.php(687): ResourceLoaderModule->buildContent(DerivativeResourceLoaderContext)
#20 /../w/includes/resourceloader/ResourceLoaderModule.php(841): ResourceLoaderModule->getModuleContent(DerivativeResourceLoaderContext)
#21 /../w/includes/resourceloader/ResourceLoader.php(667): ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)
#22 [internal function]: ResourceLoader->{closure}(string)
#23 /../w/includes/resourceloader/ResourceLoader.php(680): array_map(Closure, array)
#24 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(434): ResourceLoader->getCombinedVersion(DerivativeResourceLoaderContext, array)
#25 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(407): ResourceLoaderStartUpModule->getAllModuleHashes(DerivativeResourceLoaderContext)
#26 /../w/includes/resourceloader/ResourceLoaderModule.php(844): ResourceLoaderStartUpModule->getDefinitionSummary(DerivativeResourceLoaderContext)
#27 /../w/includes/resourceloader/ResourceLoader.php(667): ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)
#28 [internal function]: ResourceLoader->{closure}(string)
#29 /../w/includes/resourceloader/ResourceLoader.php(680): array_map(Closure, array)
#30 /../w/includes/resourceloader/ResourceLoader.php(760): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#31 /../w/load.php(53): ResourceLoader->respond(ResourceLoaderContext)
```
### Where?

https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Modifications_r%C3%A9centes

### Why?

Because you attempt to access ` User->getOption(string)` via `BootstrapComponents\ParserOutputHelper->detectSkinInUse()` during `ResourceLoaderStartUpModule`.

There are some hints and suggestions in phab on how to resolve this pesky issue.

**Comment by oetterer** [comment]
Thank you very much for reporting in such extraordinary detail!

_Unfortunately_ this problems seems to occur only in conjunction with Extension:CodeMirror, and only on MW 1.30+. Which makes catching the underlying problem tricky. And frankly, I think that using the `RequestContext` to get the Skin should never cause this cascade.

Nevertheless, I added a safety check to fix this. Will be included in next release.

**Comment by kghbln** [comment]
@oetterer Even after updating to 1.2.0 I get this via console:

```
[f1ab922c38505a3136567f98] /w/load.php?debug=false&lang=de&modules=startup&only=scripts&skin=chameleon   BadMethodCallException from line 847 of /../w/includes/session/SessionManager.php: Sessions are disabled for this entry point
Backtrace:
#0 /../w/includes/session/SessionManager.php(195): MediaWiki\Session\SessionManager->getSessionFromInfo(MediaWiki\Session\SessionInfo, WebRequest)
#1 /../w/includes/WebRequest.php(735): MediaWiki\Session\SessionManager->getSessionForRequest(WebRequest)
#2 /../w/includes/user/User.php(1231): WebRequest->getSession()
#3 /../w/includes/user/User.php(408): User->loadFromSession()
#4 /../w/includes/user/User.php(5266): User->load()
#5 /../w/includes/user/User.php(2884): User->loadOptions()
#6 /../w/includes/context/RequestContext.php(423): User->getOption(string)
#7 /../w/extensions/BootstrapComponents/src/ParserOutputHelper.php(250): RequestContext->getSkin()
#8 /../w/extensions/BootstrapComponents/src/ParserOutputHelper.php(103): BootstrapComponents\ParserOutputHelper->detectSkinInUse(boolean)
#9 [internal function]: BootstrapComponents\ParserOutputHelper->__construct(Parser)
#10 /../w/extensions/BootstrapComponents/src/ApplicationFactory.php(233): ReflectionClass->newInstanceArgs(array)
#11 /../w/extensions/BootstrapComponents/src/ApplicationFactory.php(159): BootstrapComponents\ApplicationFactory->getApplication(string, Parser)
#12 /../w/extensions/BootstrapComponents/src/Hooks/ParserFirstCallInit.php(78): BootstrapComponents\ApplicationFactory->getParserOutputHelper(Parser)
#13 /../w/extensions/BootstrapComponents/src/Setup.php(235): BootstrapComponents\Hooks\ParserFirstCallInit->__construct(Parser, BootstrapComponents\ComponentLibrary, BootstrapComponents\NestingController)
#14 /../w/includes/Hooks.php(177): BootstrapComponents\Setup->BootstrapComponents\{closure}(Parser)
#15 /../w/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#16 /../w/includes/parser/Parser.php(337): Hooks::run(string, array)
#17 /../w/extensions/CodeMirror/ResourceLoaderCodeMirrorModule.php(70): Parser->firstCallInit()
#18 /../w/extensions/CodeMirror/ResourceLoaderCodeMirrorModule.php(32): ResourceLoaderCodeMirrorModule->getFrontendConfiguraton()
#19 /../w/includes/resourceloader/ResourceLoaderModule.php(719): ResourceLoaderCodeMirrorModule->getScript(DerivativeResourceLoaderContext)
#20 /../w/includes/resourceloader/ResourceLoaderModule.php(687): ResourceLoaderModule->buildContent(DerivativeResourceLoaderContext)
#21 /../w/includes/resourceloader/ResourceLoaderModule.php(841): ResourceLoaderModule->getModuleContent(DerivativeResourceLoaderContext)
#22 /../w/includes/resourceloader/ResourceLoader.php(667): ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)
#23 [internal function]: ResourceLoader->{closure}(string)
#24 /../w/includes/resourceloader/ResourceLoader.php(680): array_map(Closure, array)
#25 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(434): ResourceLoader->getCombinedVersion(DerivativeResourceLoaderContext, array)
#26 /../w/includes/resourceloader/ResourceLoaderStartUpModule.php(407): ResourceLoaderStartUpModule->getAllModuleHashes(DerivativeResourceLoaderContext)
#27 /../w/includes/resourceloader/ResourceLoaderModule.php(844): ResourceLoaderStartUpModule->getDefinitionSummary(DerivativeResourceLoaderContext)
#28 /../w/includes/resourceloader/ResourceLoader.php(667): ResourceLoaderModule->getVersionHash(DerivativeResourceLoaderContext)
#29 [internal function]: ResourceLoader->{closure}(string)
#30 /../w/includes/resourceloader/ResourceLoader.php(680): array_map(Closure, array)
#31 /../w/includes/resourceloader/ResourceLoader.php(760): ResourceLoader->getCombinedVersion(ResourceLoaderContext, array)
#32 /../w/load.php(53): ResourceLoader->respond(ResourceLoaderContext)
#33 {main}
```

**Comment by oetterer** [comment]
@kghbln could you please try with master again. damn overengeneering let me fumble my tested solution at the last edit.
Thanks for testing! @kghbln

**Comment by kghbln** [comment]
@oetterer Now on master: `Notice: Use of undefined constant MW_NO_SESSION - assumed 'MW_NO_SESSION' in /../w/extensions/BootstrapComponents/src/ParserOutputHelper.php on line 102
stringfalse_MW_NO_SESSION` The session issue is still there.

**Comment by oetterer** [comment]
you are too fast! :) Please try againg.

And I need a break. Apparently, my concentration is currently lacking a lot.

**Comment by kghbln** [comment]
@oetterer Done but still worries. It is getting better however something is still there. Take your time and get a break.

**Comment by oetterer** [comment]
All I can say is: It finally works without error on my dev system now. And: I can't find a mention of _BootstrapCompoments_ in the stack trace on [0]. However there is a mention of "Arrays" (see line #11). That strenghtens my believe, that CodeMirror is the culprit, and not me.

[0]: https://sandbox.semantic-mediawiki.org//w/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector&debug=true

**Comment by kghbln** [comment]
@oetterer You are right BootstrapComponents is not the transgressor but Arrays and NumerAlpha. See [T181676](https://phabricator.wikimedia.org/T181676). Have not gotten around reporting this yet.

**Comment by oetterer** [comment]
@kghbln If you do, please reference [T187769](https://phabricator.wikimedia.org/T187769)

**Comment by kghbln** [comment]
@oetterer Done with [T187794](https://phabricator.wikimedia.org/T187794). Perhaps you would like to give a shot at it since the Arrays extension is very helpful but basically unmaintained. *hope*

**Comment by oetterer** [comment]
@kghbln sounds tempting, but I can't promise anything. Besides, I still hope, we find the underlying problem in CodeMirror or core.
Nevertheless, I'm off for a week's worth of relaxation and won't be online.

**Comment by kghbln** [comment]
@oetterer 

> sounds tempting, but I can't promise anything.

No worries. However, if you are tempted at some point may appreciation will haunt you all along you future paths. :)

> Besides, I still hope, we find the underlying problem in CodeMirror or core.

Let's hope for the best, but from experience I would not count on a quick fix if at all.

**Comment by kghbln** [comment]
@oetterer https://github.com/oetterer/BootstrapComponents/commit/68b299fb7ae5fd1177de1d15a71c8ad56cc7de4b has not yet been released. What about doing a 1.2.1?

**Comment by oetterer** [comment]
@kghbln just for you!

**Comment by kghbln** [comment]
Cool! Apart from that. I am sure that others will find this extension useful, too. Thus it will not be just for me. :)
